export const testData = [
  {
    method: 'abs(x)',
    inputValid: 'x = liczba rzeczywista',
    inputInvalid: 'string, null',
    outputValid: 'liczby dodatnie lub zero',
    outputInvalid: 'string, null',
    boundaries: '{-∞, ∞}',
  },
  {
    method: 'sqrt(x)',
    inputValid: 'x >= 0',
    inputInvalid: 'x < 0, string, null',
    outputValid: 'liczby rzeczywiste',
    outputInvalid: 'string, null',
    boundaries: '{-1, 0}',
  },
  {
    method: 'log(x)',
    inputValid: 'x >= 0',
    inputInvalid: 'x < 0, null, string',
    outputValid: 'liczby rzeczywiste',
    outputInvalid: 'string, null',
    boundaries: '{-1, 0}',
  },
  {
    method: 'factorial(x)',
    inputValid: 'x >= 0',
    inputInvalid: 'x < 0',
    outputValid: 'liczby rzeczywiste',
    outputInvalid: 'string, null',
    boundaries: '{-1, 0}',
  },
  {
    method: 'pow(x, y)',
    inputValid: 'liczby rzeczywiste',
    inputInvalid: 'null, string',
    outputValid: 'liczby rzeczywiste',
    outputInvalid: 'string, null',
    boundaries: '{-∞, ∞}',
  },

  {
    method: 'mod(a, b)',
    inputValid: 'liczby rzeczywiste',
    inputInvalid: 'null, string',
    outputValid: 'liczby rzeczywiste',
    outputInvalid: 'string, null',
    boundaries: '{-∞, ∞}',
  },
  {
    method: 'and(x, y)',
    inputValid: 'liczby rzeczywiste, boolean',
    inputInvalid: 'string, null',
    outputValid: 'boolean',
    outputInvalid: 'liczby, string, null',
    boundaries: '{-∞, ∞}',
  },
  {
    method: 'not(arr)',
    inputValid: 'liczby rzeczywiste, boolean',
    inputInvalid: 'string, nulll',
    outputValid: 'boolean',
    outputInvalid: 'liczby, string, null',
    boundaries: '{-∞, ∞};',
  },
  {
    method: 'or(x, y)',
    inputValid: 'liczby rzeczywiste, boolean',
    inputInvalid: 'string, null',
    outputValid: 'boolean',
    outputInvalid: 'liczby, string, null',
    boundaries: '{-∞, ∞}',
  },
  {
    method: 'xor(x, y)',
    inputValid: 'liczby rzeczywiste, boolean',
    inputInvalid: 'string, null',
    outputValid: 'boolean',
    outputInvalid: 'liczby, string, null',
    boundaries: '{-∞, ∞}',
  },
];
